"""Object ids generated by the client (RTO14) and parsed by it (RTO6b)."""

from __future__ import annotations

import base64
import hashlib
import os

# 12 random bytes base64-encode to 16 characters, the RTLCV4d/RTLMV4g minimum
_NONCE_ENTROPY_BYTES = 12


def generate_object_id(object_type: str, initial_value: str, nonce: str, timestamp_ms: int) -> str:
    """RTO14: `[type]:[hash]@[timestamp]`, where the hash is the URL-safe, unpadded base64 of
    the SHA-256 of `initial_value:nonce` (RTO14b).

    `object_type` is `'map'` or `'counter'` (RTO14a1).
    """
    digest = hashlib.sha256(f'{initial_value}:{nonce}'.encode()).digest()  # RTO14b1
    hash_part = base64.urlsafe_b64encode(digest).decode('ascii').rstrip('=')  # RTO14b2
    return f'{object_type}:{hash_part}@{int(timestamp_ms)}'  # RTO14c


def generate_nonce() -> str:
    """RTLCV4d, RTLMV4g: a random string of at least 16 characters."""
    return base64.urlsafe_b64encode(os.urandom(_NONCE_ENTROPY_BYTES)).decode('ascii')


def object_type_of(object_id: str) -> str:
    """RTO6b1: the type an object id names, the part before the first `:`."""
    return object_id.split(':', 1)[0]
